### ISSUE TITLE
Delete README.md in the old repro and add a link to this one?

### ISSUE THREAD

**Issue by hrydgard** [rust-mobile/ndk#194]
I googled "cargo apk" and ended up on the archived repository https://github.com/rust-windowing/android-rs-glue .

Since so much of it still looks ok, I failed to noticed that it was archived, and followed the cargo.toml example documented further down on the front page there. That did not work out well.

In this new repo, you have to enter the cargo-apk folder to see the toml example. Maybe that's why google still sends you to the old repo? Either way, there probably should be an obvious link to the cargo-apk folder, and preferably the README.md on the old repo should be cleared out to reduce it's search engine mojo, and only have a really loud, big and obnoxious link to this new one :)

**Comment by MarijnS95** [comment]
We can - should - probably enlarge the deprecation notice, perhaps even delete the rest of the README and point readers to a commit prior to removal if they want to read the "archived" content.

**Comment by MarijnS95** [comment]
Side-note: it doesn't seem like I have the necessary rights to temporarily un-archive that repo and make the desired change. One of the other maintainers will have to do so.

**Comment by MarijnS95** [comment]
>  Either way, there probably should be an obvious link to the cargo-apk folder

How about adding a little "usage" section ~above~/below the "hello world" section, pointing to the various crate readme's explaining where to go from there after having copy-pasted and successfully ran the "hello world" example?

You're more than welcome to send a PR in this regard, assuming you probably have a better insight in how to pose this information in a useful and accessible way.

**Comment by hrydgard** [comment]
OK, will try to find some time for that. Like you, I of course can't do anything about the old repo.

**Comment by MarijnS95** [comment]
The repo now also has a massive yellow header:

> This repository has been archived by the owner before Nov 9, 2022. It is now read-only.

And the small deprecation notice in the README remains. Don't think there's anything actionable remaining here.
