### ISSUE TITLE
Update `num_enum` crate to `0.6.1`

### ISSUE THREAD

**Issue by kchibisov** [rust-mobile/ndk#392]
This is also applicable to `android-activity`.

This is causing duplicates on the `syn` dependency.

**Comment by MarijnS95** [comment]
@kchibisov how quickly do you want to resolve this? `num_enum` is used in our public API so that requires another breaking change... and I'd like to cram in a few more breaking changes if we have to do a semver-breaking release bump anyway.

**Comment by MarijnS95** [comment]
@kchibisov looking at https://github.com/rust-mobile/android-activity/pull/108 `0.7` just dropped... do you want that for `winit` or not?

**Comment by kchibisov** [comment]
You can pick latest, I don't really care.
