### ISSUE TITLE
Investigate `MediaFormat` mutability / lifetimes

### ISSUE THREAD

**Issue by MarijnS95** [rust-mobile/ndk#451]
Barely any of the `MediaFormat` functions from the "safe" `MediaCodec` PR #216 take `self` as `mut`, even though there are quite a few functions that return borrows from pointers which are very likely invalidated when the `MediaFormat` is modified in some way. Even "strict getters" have the ability to invalidate previously returned results and should be considered `mut` for that case.

[See for example `toString()`](https://developer.android.com/ndk/reference/group/media#amediaformat_tostring) which is mentioned in https://github.com/rust-mobile/ndk/pull/450:

> The returned string is owned by the format, and remains valid until the next call to toString, or until the format is deleted.

Fortunately this function is not directly exposed to users, only via `Display` which copies the resulting string via `write_str()` in the same function where `AMediaFormat_toString()` is called.

[`getString()`](https://developer.android.com/ndk/reference/group/media#amediaformat_getstring) has the same reentrancy limitation:

> The returned string is owned by the format, and remains valid until the next call to getString, or until the format is deleted.

[`getBuffer()`](https://developer.android.com/ndk/reference/group/media#amediaformat_getbuffer) strangely is not documented to be invalidated on repeated invocations, only when it (obviously) is removed from the `MediaFormat`:

> The returned data is owned by the format and remains valid as long as the named entry is part of the format.

Note that I'm implying for both strings and buffers that they are invalidated when the same key is set to a different string/buffer/value (and maybe even when _another_ key is changed).

---

Given these notions I _**think**_ we should make all `set` functions, _and `fn string()` `mut`.

CC @zarik5 @spencercw in case I'm missing something in my observation.

**Comment by MarijnS95** [comment]
Thanks @spencercw! Mind reviewing the linked PR?

Note that I've asked for some extra clarification upstream, as I can think of way too many loopholes with these functions that clobber our implementation in Rust:

https://issuetracker.google.com/issues/300602767#comment9

**Comment by spencercw** [comment]
Might be worth perusing the [Android source code](https://cs.android.com/android/platform/superproject/main/+/main:frameworks/av/media/ndk/NdkMediaFormat.cpp) which should answer your questions. Doesn't help that these details are not documented of course.

**Comment by MarijnS95** [comment]
@spencercw while it does answer our questions, I prefer to leave source-code-diving as an exercise to the AOSP developers, and have them set these implicit assumptions in stone by describing it more clearly in a documentation field.
