### ISSUE TITLE
Support of building .aab files

### ISSUE THREAD

**Issue by enfipy** [rust-mobile/ndk#81]
Currently, it's possible to build .apk files only but the [modern way](https://android-developers.googleblog.com/2020/06/introducing-google-play-asset-delivery.html) to distribute an Android app is through aab (Android App Bundle).

To build *.aab files the following links may be useful:
* What aab is: https://developer.android.com/guide/app-bundle
* How to build in the Android studio: https://developer.android.com/studio/run#reference
* Official doc for building aab from CLI: https://developer.android.com/studio/build/building-cmdline
* A better variant in my opinion: https://musteresel.github.io/posts/2019/07/build-android-app-bundle-on-command-line.html

As far as I understand, cargo-apk uses aapt underneath. I hope this will be not a big problem to add support for *.aab. Any suggestions?

**Comment by Heraclito-Q-Saldanha** [comment]
any news?

**Comment by enfipy** [comment]
> any news?

We ended up building our tool that supports "native" (without Gradle) build of `.aab` files: https://github.com/dodorare/crossbow. We adapted a bunch of code from cargo-apk - so it should work pretty like the same as this.

**Comment by MarijnS95** [comment]
> We ended up building our tool [..] We adapted a bunch of code from cargo-apk

A famous XKCD comes to mind... Now there's one more _competing_ implementation for building Rust Android apps.

**Comment by dvc94ch** [comment]
xbuild also supports building aab's. Closing this for now as it's in the wrong repo anyway.

**Comment by MarijnS95** [comment]
@dvc94ch it wasn't the wrong repo, we just split it out well after this issue was posted. We could also transfer it to the new `cargo-apk` repo (and close it regardless because `xbuild` takes care of this and is the successor of `cargo-apk`).

**Comment by MarijnS95** [comment]
Transferring is nice for cleanliness, just making sure the original reporter isn't scared away by "it's in the wrong repo anyway" :grin:
